### ISSUE TITLE
formatQuery error with json_without_ids formatter - Uncaught TypeError: Object(...)

### ISSUE THREAD

**Issue by bumi** [react-querybuilder/react-querybuilder#147]
I am getting the following error when I try to format a query object using `json_without_ids` .
This happens in the version ~~3.4.1 and~~ 3.5  -- update: it only breaks in 3.5.0 and works in 3.4.0

### error: 

query-builder.jsx.js:26 is my file - line 26 is the `console.log(formatQuery(query, 'json_without_ids'));`
```
index.js:164 Uncaught TypeError: Object(...) is not a function
    at t (index.js:164)
    at a (index.js:168)
    at Module../app/javascript/query-builder.jsx.js (query-builder.jsx.js:26)
    at __webpack_require__ (bootstrap:19)
    at Module../app/javascript/packs/application.js (application.js:12)
    at __webpack_require__ (bootstrap:19)
    at bootstrap:83
    at bootstrap:83
```

### code:

```js
// example from the readme
const query = {
  id: 'g-b6SQ6WCcup8e37xhydwHE',
  rules: [
    {
      id: 'r-zITQOjVEWlsU1fncraSNn',
      field: 'firstName',
      value: 'Steve',
      operator: '='
    },
    {
      id: 'r-zVx7ARNak3TCZNFHkwMG2',
      field: 'lastName',
      value: 'Vai',
      operator: '='
    }
  ],
  combinator: 'and',
  not: false
};

console.log(formatQuery(query, 'json_without_ids'));
```

**Comment by bumi** [comment]
wondering if that is related to: https://github.com/lodash/lodash/issues/4610

from the stacktrace:
```js
if ("json_without_ids" === e) return JSON.stringify(function t(n) {
      var r = Object(i.cloneDeep)(n);
      return delete r.id, p(r) && (r.rules = r.rules.map(function (n) {
        return t(n);
      })), r;
    }(t));
```

**Comment by jakeboone02** [comment]
I'm having trouble reproducing the issue.  See [this codesandbox](https://codesandbox.io/s/react-querybuilder-147-c9ju1?file=/src/App.js), which works without an error.  Can you set up a codesandbox to reproduce it?

**Comment by bumi** [comment]
@jakeboone02 hmm, yes strange. I can also not reproduce it in the codesandbox. 
wondering what this could cause to fail `Object(i.cloneDeep)(n)` ?

**Comment by loris** [comment]
Can reproduce it too. The codesandbox probably polyfills some stuff which are not available in browsers

**Comment by bumi** [comment]
I am using it in a Rails app (sadly closed source right now) I've removed all other dependencies -  so only the rails webpack build process (which also includes some babel?) is left...  and get this error. 

I do not get the error when I use the code from the demo. 

any idea how I can further debug this?

**Comment by bumi** [comment]
So I still have this error and fail to further debug it. I have no idea what combination causes or solves it. any hints on how to further investigate this?

**Comment by dig** [comment]
I'm able to reproduce it as well.

**Comment by rsousa88** [comment]
+1 having the issue in v3.5.1. Any fix/workaround for this?

**Comment by jakeboone02** [comment]
This has been fixed in 40ce711d0 which will be merged into master soon.
